### ISSUE TITLE
dpark运行出错

### ISSUE THREAD

**Issue by lansane** [douban/dpark#58]
import sys
sys.path.append('../')
from dpark import DparkContext
dpark = DparkContext()
file = dpark.textFile("./tmp/words.txt")
words = file.flatMap(lambda x:x.split()).map(lambda x:(x,1))
wc = words.reduceByKey(lambda x,y:x+y).collectAsMap()
## print wc

Traceback (most recent call last):
  File "wc_1.py", line 7, in <module>
    wc = words.reduceByKey(lambda x,y:x+y).collectAsMap()
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\rdd.py", line 502, in collectAsMap
    for v in self.ctx.runJob(self, lambda x:list(x)):
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\context.py", line 264, in runJob
    for it in self.scheduler.runJob(rdd, func, partitions, allowLocal):
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\schedule.py", line 333, in runJob
    [l[-1] for l in stage.outputLocs])
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\shuffle.py", line 353, in registerMapOutputs
    self.client.call(SetValueMessage('shuffle:%s' % shuffleId, locs))
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\tracker.py", line 112, in call
    sock.connect(self.addr)
  File "zmq/backend/cython/socket.pyx", line 514, in zmq.backend.cython.socket.S
ocket.connect (zmq\backend\cython\socket.c:5376)
zmq.error.ZMQError: Invalid argument
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "F:\install\acond\lib\atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\context.py", line 281, in stop
    env.stop()
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\env.py", line 92, in stop
    self.trackerServer.stop()
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\tracker.py", line 49, in stop
    sock.connect(self.addr)
  File "zmq/backend/cython/socket.pyx", line 514, in zmq.backend.cython.socket.S
ocket.connect (zmq\backend\cython\socket.c:5376)
ZMQError: Invalid argument
Error in sys.exitfunc:
Traceback (most recent call last):
  File "F:\install\acond\lib\atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\context.py", line 281, in stop
    env.stop()
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\env.py", line 92, in stop
    self.trackerServer.stop()
  File "F:\install\acond\lib\site-packages\dpark-0.2.2-py2.7-win-amd64.egg\dpark
\tracker.py", line 49, in stop
    sock.connect(self.addr)
  File "zmq/backend/cython/socket.pyx", line 514, in zmq.backend.cython.socket.S
ocket.connect (zmq\backend\cython\socket.c:5376)
zmq.error.ZMQError: Invalid argument

**Comment by windreamer** [comment]
看起来是`zmq` 安装有问题，需要本机的`zmq-dev`和`pyzmq`版本尽可能能对应上
