### ISSUE TITLE
dpark  multiprocess 下stage 是不是不能并行

### ISSUE THREAD

**Issue by NHZlX** [douban/dpark#61]
看了点源码,  发现可运行的stage之间 是不是不能并行, 只支持某stage下tasks的并行. 求问是真的不能并行还是我忽略了些什么...

**Comment by windreamer** [comment]
`Stage` 包含若干个 `Job`
`Stage` 本身是串行执行的，表示执行序列中的一个阶段
但是一个`Stage`中的若干`Job`是可以并行的，这个要看各个`Job`之间的执行关系
`Task`是`Job`的分布式执行单位

举一个不严谨的例子
```python
from dpark import DparkContext
dpark = DparkContext()

rdd = dpark.makeRDD(range(10),3).sort(reverse=True)
rdd1 = dpark.makeRDD(range(5, 15),3).sort(reverse=True)

print rdd.union(rdd1).map(lambda x: (x, 1)).reduceByKey(lambda x, y: x+ y).collectAsMap()
```

其中两个`sort`的第二阶段也就是reduce阶段是并行执行的

```
$ python test.py -m process
2016-05-23 17:51:27,295 [INFO] [dpark.schedule] Got a job with 3 tasks: <MappedRDD <MapPartitionsRDD <ParallelCollection 10>>>
2016-05-23 17:51:27,318 [INFO] [dpark.schedule] Job finished in 0.0 seconds                    
2016-05-23 17:51:27,434 [INFO] [dpark.schedule] Got a job with 3 tasks: <MappedRDD <MapPartitionsRDD <ParallelCollection 10>>>
2016-05-23 17:51:27,440 [INFO] [dpark.schedule] Job finished in 0.0 seconds                    
2016-05-23 17:51:27,565 [INFO] [dpark.schedule] Got a job with 3 tasks: <MappedRDD <ParallelCollection 10>>
2016-05-23 17:51:27,578 [INFO] [dpark.schedule] Got a job with 3 tasks: <MappedRDD <ParallelCollection 10>>
2016-05-23 17:51:27,611 [INFO] [dpark.schedule] Job finished in 0.0 seconds                    
2016-05-23 17:51:27,683 [INFO] [dpark.schedule] Got a job with 4 tasks: <MappedRDD <UnionRDD 2 <MapPartitionsRDD <FlatMappedRDD <ShuffledRDD <MappedRDD <ParallelCollection 10>>>>> ...>>
2016-05-23 17:51:27,827 [INFO] [dpark.schedule] Job finished in 0.1 seconds                    
2016-05-23 17:51:27,885 [INFO] [dpark.schedule] Got a job with 4 tasks: <ShuffledRDD <MappedRDD <UnionRDD 2 <MapPartitionsRDD <FlatMappedRDD <ShuffledRDD <MappedRDD <ParallelCollection 10>>>>> ...>>>
2016-05-23 17:51:28,011 [INFO] [dpark.schedule] Job finished in 0.1 seconds                    
{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 10: 1, 11: 1, 12: 1, 13: 1, 14: 1}
```

**Comment by xunzhang** [comment]
@NHZlX stage间前后依赖咋并行？

**Comment by zzl0** [comment]
@xunzhang 他问的应该是没有依赖的 stage 之间（即「可运行的 stage」的之间）

**Comment by xunzhang** [comment]
@zzl0 ，ok。 @NHZlX ，spark提供的是单stage中task的并行。当然可以同时跑两个脚本：`rdd`和`rdd1`，也可以自己开进程做，这是上层应用层的事儿。

**Comment by NHZlX** [comment]
@windreamer 你的例子我是明白的, 其实就是一个stage中多个tasks并行. 虽然还没有看mesos 下的实现, 我想问mesos下 无依赖stage 之间也是串行的么

**Comment by NHZlX** [comment]
在我本上运行 demo时候， 会在text search example 卡住， ctr+c后的 exception 为：
^Clogging
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    print 'logging', log.count()
  File "/home/xzl/hg/spark/dpark/dpark/rdd.py", line 368, in count
    return sum(self.ctx.runJob(self, lambda x: sum(1 for i in x)))
  File "/home/xzl/hg/spark/dpark/dpark/context.py", line 263, in runJob
    for it in self.scheduler.runJob(rdd, func, partitions, allowLocal):
  File "/home/xzl/hg/spark/dpark/dpark/schedule.py", line 292, in runJob
    submitStage(finalStage)
  File "/home/xzl/hg/spark/dpark/dpark/schedule.py", line 254, in submitStage
    submitMissingTasks(stage)
  File "/home/xzl/hg/spark/dpark/dpark/schedule.py", line 290, in submitMissingTasks
    self.submitTasks(tasks)
  File "/home/xzl/hg/spark/dpark/dpark/schedule.py", line 397, in submitTasks
    _, reason, result, update = run_task(task, self.nextAttempId())
  File "/home/xzl/hg/spark/dpark/dpark/schedule.py", line 376, in run_task
    result = task.run(aid)
  File "/home/xzl/hg/spark/dpark/dpark/task.py", line 52, in run
    return self.func(self.rdd.iterator(self.split))
  File "/home/xzl/hg/spark/dpark/dpark/rdd.py", line 368, in <lambda>
    return sum(self.ctx.runJob(self, lambda x: sum(1 for i in x)))
  File "/home/xzl/hg/spark/dpark/dpark/rdd.py", line 368, in <genexpr>
    return sum(self.ctx.runJob(self, lambda x: sum(1 for i in x)))
  File "/home/xzl/hg/spark/dpark/dpark/util.py", line 111, in _
    for r in result:
  File "/home/xzl/hg/spark/dpark/dpark/cache.py", line 205, in getOrCompute
    cachedVal = self.cache.get(key)
  File "/home/xzl/hg/spark/dpark/dpark/cache.py", line 57, in get
    locs = self.tracker.getCacheUri(rdd_id, index)
  File "/home/xzl/hg/spark/dpark/dpark/cache.py", line 195, in getCacheUri
    return self.client.call(GetValueMessage('cache:%s-%s' % (rdd_id, index)))
  File "/home/xzl/hg/spark/dpark/dpark/tracker.py", line 116, in call
    return sock.recv_pyobj()
  File "/home/xzl/.virtualenvs/dpark/local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 436, in recv_pyobj
    s = self.recv(flags)
  File "zmq/backend/cython/socket.pyx", line 674, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6971)
  File "zmq/backend/cython/socket.pyx", line 708, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6763)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1931)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7222)
KeyboardInterrupt
而且得 按两次 ctr+c
在台式机上没啥问题。。。

**Comment by windreamer** [comment]
@NHZlX 

多个无依赖的Stage是有可能可以并行的，DPark会尽最大可能将可以并行执行的stage来同时计算
cf： https://github.com/douban/dpark/blob/master/dpark/schedule.py#L336

**Comment by windreamer** [comment]
后一个问题看上去确实是没有收到TrackerServer的回包，这个地方目前没有超时可能是不太合理，
如果方便的话可以帮忙再开一个issue记录一下，我会在这里加个超时

至于为什么没收到回包，我这里也不清楚...信息有点少，很难确定。
