### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by ahjdzx** [douban/dpark#63]
```
$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to DPark.egg-info/requires.txt
writing DPark.egg-info/PKG-INFO
writing top-level names to DPark.egg-info/top_level.txt
writing dependency_links to DPark.egg-info/dependency_links.txt
reading manifest file 'DPark.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'dpark/porable_hash.pyx'
writing manifest file 'DPark.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'dpark/portable_hash.c' Cython extension (up-to-date)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/decorator.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/hotcounter.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/schedule.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/__init__.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/util.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/rdd.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/cache.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/tracker.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/bagel.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/executor.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/task.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/bitindex.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/table.py -> build/bdist.linux-x86_64/egg/dpark
creating build/bdist.linux-x86_64/egg/dpark/moosefs
copying build/lib.linux-x86_64-2.7/dpark/moosefs/__init__.py -> build/bdist.linux-x86_64/egg/dpark/moosefs
copying build/lib.linux-x86_64-2.7/dpark/moosefs/consts.py -> build/bdist.linux-x86_64/egg/dpark/moosefs
copying build/lib.linux-x86_64-2.7/dpark/moosefs/cs.py -> build/bdist.linux-x86_64/egg/dpark/moosefs
copying build/lib.linux-x86_64-2.7/dpark/moosefs/utils.py -> build/bdist.linux-x86_64/egg/dpark/moosefs
copying build/lib.linux-x86_64-2.7/dpark/moosefs/master.py -> build/bdist.linux-x86_64/egg/dpark/moosefs
copying build/lib.linux-x86_64-2.7/dpark/env.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/broadcast.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/serialize.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/tabular.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/mutable_dict.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/context.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/conf.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/accumulator.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/dstream.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/hyperloglog.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/portable_hash.so -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/job.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/dependency.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/shuffle.py -> build/bdist.linux-x86_64/egg/dpark
copying build/lib.linux-x86_64-2.7/dpark/portable_hash.pyx -> build/bdist.linux-x86_64/egg/dpark
byte-compiling build/bdist.linux-x86_64/egg/dpark/decorator.py to decorator.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/hotcounter.py to hotcounter.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/schedule.py to schedule.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/rdd.py to rdd.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/cache.py to cache.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/tracker.py to tracker.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/bagel.py to bagel.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/executor.py to executor.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/task.py to task.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/bitindex.py to bitindex.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/table.py to table.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/moosefs/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/moosefs/consts.py to consts.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/moosefs/cs.py to cs.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/moosefs/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/moosefs/master.py to master.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/env.py to env.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/broadcast.py to broadcast.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/serialize.py to serialize.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/tabular.py to tabular.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/mutable_dict.py to mutable_dict.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/context.py to context.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/conf.py to conf.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/accumulator.py to accumulator.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/dstream.py to dstream.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/hyperloglog.py to hyperloglog.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/job.py to job.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/dependency.py to dependency.pyc
byte-compiling build/bdist.linux-x86_64/egg/dpark/shuffle.py to shuffle.pyc
creating stub loader for dpark/portable_hash.so
byte-compiling build/bdist.linux-x86_64/egg/dpark/portable_hash.py to portable_hash.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/dquery -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/executor.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/scheduler.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/drun -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/mrun -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/dgrep -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/dquery to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/executor.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/scheduler.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/drun to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/mrun to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/dgrep to 755
copying DPark.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DPark.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DPark.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DPark.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DPark.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DPark.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/DPark-0.3.2-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing DPark-0.3.2-py2.7-linux-x86_64.egg
removing '/usr/lib64/python2.7/site-packages/DPark-0.3.2-py2.7-linux-x86_64.egg' (and everything under it)
creating /usr/lib64/python2.7/site-packages/DPark-0.3.2-py2.7-linux-x86_64.egg
Extracting DPark-0.3.2-py2.7-linux-x86_64.egg to /usr/lib64/python2.7/site-packages
DPark 0.3.2 is already the active version in easy-install.pth
Installing dquery script to /usr/bin
Installing executor.py script to /usr/bin
Installing scheduler.py script to /usr/bin
Installing drun script to /usr/bin
Installing mrun script to /usr/bin
Installing dgrep script to /usr/bin

Installed /usr/lib64/python2.7/site-packages/DPark-0.3.2-py2.7-linux-x86_64.egg
Processing dependencies for DPark==0.3.2
Searching for psutil
Reading https://pypi.python.org/simple/psutil/
^[[B^[[B^[Best match: psutil 4.3.0
Downloading https://pypi.python.org/packages/22/a8/6ab3f0b3b74a36104785808ec874d24203c6a511ffd2732dd215cf32d689/psutil-4.3.0.tar.gz#md5=ca97cf5f09c07b075a12a68b9d44a67d
Processing psutil-4.3.0.tar.gz
Writing /tmp/easy_install-T5wfHJ/psutil-4.3.0/setup.cfg
Running psutil-4.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-T5wfHJ/psutil-4.3.0/egg-dist-tmp-_tuYcX
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    'examples/dgrep',
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 117, in do_egg_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 380, in run

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 610, in easy_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 661, in install_item

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 709, in process_distribution

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 836, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1081, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1093, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 629, in easy_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 659, in install_item

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 842, in install_eggs

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1070, in build_and_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1056, in run_setup

  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 240, in run_setup
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 193, in setup_context
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 152, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 126, in __exit__
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 110, in dump
MemoryError
```

**Comment by zzl0** [comment]
@ahjdzx 看起来 [setuptools 的问题](https://github.com/giampaolo/psutil/issues/723)，建议通过 `pip install -r req.txt` 来安装 DPark 的依赖。

**Comment by ahjdzx** [comment]
@zzl0  OK, 装好了，Thx!
