### ISSUE TITLE
lz4wrapper.py没有更新

### ISSUE THREAD

**Issue by ellenzhu** [douban/dpark#82]
lz4wrapper.py最新版本和链接里下载的代码不一样，导致dpark安装失败。人工copy到最新代码才能安装成功。。。。

**Comment by youngsofun** [comment]
“链接”  是什么意思？ release 中的下载 压缩包的链接吗？

**Comment by ellenzhu** [comment]
release里面直接下载的压缩包，dpark-0.4.x .tar.gz里此文件没更新

**Comment by Veallym0n** [comment]
```
>>> import dpark
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/dpark/__init__.py", line 2, in <module>
    from .context import DparkContext, parser as optParser
  File "/usr/lib64/python2.7/site-packages/dpark/context.py", line 9, in <module>
    from dpark.rdd import *
  File "/usr/lib64/python2.7/site-packages/dpark/rdd.py", line 28, in <module>
    from dpark.dependency import *
  File "/usr/lib64/python2.7/site-packages/dpark/dependency.py", line 4, in <module>
    from dpark.util import portable_hash
  File "/usr/lib64/python2.7/site-packages/dpark/util.py", line 35, in <module>
    from dpark.lz4wrapper import compress, decompress
  File "/usr/lib64/python2.7/site-packages/dpark/lz4wrapper.py", line 11, in <module>
    compress = lz4.compress
AttributeError: 'module' object has no attribute 'compress'
```
好像是有这个毛病。。。。
python2.7, pip install, 源是douban..... 然后后出现了问题，lz4已经是2.0.2..从lz4变成了lz4.frame....然后貌似没默认装上py-lz4framed....

**Comment by ariesdevil** [comment]
@ellenzhu @Veallym0n 已发新版，pip 安装前请参照 readme 安装系统依赖。
